spring:
  profiles: common

tencent:
  cloud:
    appId: 1111
    secretId: 1111
    secretKey: 1111
    region-public: 1111
    bucket-public: 1111
    region-private: 1111
    bucket-private: 1111
    face:
      groupName: 1111
      region: 1111

  map: 
    key: 1111
wx:
  app-id: 11111
  app-secret: 11111
  mch-id: 11111
  key: 11111
  cert-path: 11111

minio:
  endpoint: http://192.168.47.129:9000
  access-key: root
  secret-key: abc123456

